### ISSUE TITLE
Windows defender flags it as a virus

### ISSUE THREAD

**Issue by valignatev** [valignatev/socd#1]
Idk if I want to do anything about it, but it's definitely worth to at least see if there's an easy way to tell it that we're good.

**Comment by fifty-six** [comment]
fwiw the released executable triggers under [virustotal](https://www.virustotal.com/gui/file/a0f468fa1275d501336babff4b5e6ae49a0ebfef8f1bbd521f55689351c0b029/detection) for me, but when [recompiling with stock clang it doesn't](https://www.virustotal.com/gui/file/a0f468fa1275d501336babff4b5e6ae49a0ebfef8f1bbd521f55689351c0b029/detection), so just using a different compiler is a workaround

**Comment by valignatev** [comment]
Just checked it out, compiling it with clang triggers some antivirus on virustotal but since it's not wdefender it's much better. I'll attach new binary in releases shortly, thanks a lot for pointing it out!
