### ISSUE TITLE
It should work for down+up too in addition to left+right

### ISSUE THREAD

**Issue by greanthai420** [valignatev/socd#12]
Guilty Gear Strive's internal socd cleaner makes it so that down+up=neutral, this software can only fix left+right

**Comment by valignatev** [comment]
Allowing customization of left+right and up+down arbitrarily is on todo list. So in the end you'll be able to configure it however you want: https://github.com/valignatev/socd/issues/7 You can track that issue instead

**Comment by greanthai420** [comment]
sorry, it was just me not understanding how to configure.
i need to make changes in socd.conf before running the software.
