### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by doonoo** [valignatev/socd#13]
You probably don't use linux, but I tried this with fightcade2 (3rd strike) and when I press left and right simultaneously, it just outputted left. So I don't think it works through wine.

**Comment by valignatev** [comment]
I use linux a lot, just don't game on linux as much as I used to. I really doubt wine implements low level keyboard hooks, yeah. Supporting linux and mac is something I have on my backburner, but it's like way down in my todo list. 

I'll leave this issue opened to state my intention to support Linux in the future though :)
