### ISSUE TITLE
SOCD not working

### ISSUE THREAD

**Issue by Psyonicpanda** [valignatev/socd#19]
Hello,

Had an issue with the program not functioning correctly. I had entered my custom keys (ASD Space) and set the cleaner to custom but I still get a neutral input with holding A+D or S+Space. Here are my conf settings:
41
44
VK_SPACE
53

I also tried it as just SPACE without the VK or _

**Comment by valignatev** [comment]
Space is 20, not VK_SPACE. Also you shouldn't click "custom", all you need to do is to restart the program after you change the config and it theoretically should work

**Comment by valignatev** [comment]
oh if it messes up your browser inputs then it definitely works. The reason why it might not work in any particular game is if that game explicitly ignores synthetic inputs. I know for a fact that at least source games do that (so portal, half-life2 and friends). I was planning to experiment with using scancodes instead of virtual key codes to see if it circumvents the game behavior. I'm gonna keep this issue open until I confirm if that's the case, thanks for another possible example!

**Comment by Psyonicpanda** [comment]
I played fighting games on a hitbox controller that has built in SOCD and that has never been an issue, so I'm not sure if it's a game specific issue. I tried it on multiple other fighting games and get the same result on keyboard. The biggest thing is doing "charge moves". You have to hold down and then press up+a button to get the move to come out. You should be able to continue holding down when you tap up and get your move. Might just try to get my hitbox fixed instead but if you have any questions that might help you, let me know!

**Comment by Psyonicpanda** [comment]
I can post a quick video with a command overlay of what I'm inputting and what the game sees, if that helps.

**Comment by valignatev** [comment]
yeah hitboxes implement that on a driver level, and this socd cleaner just sends signals to windows, that applications might choose to ignore. So totally different implementation. Yeah feel free to send a video, but just make sure that the command overlay is not coming from the game but is a separate program that records the inputs

**Comment by Psyonicpanda** [comment]
So I went and tried it out. It does work with Persona and with USF4 now. Still does not work with Melty. I'll take a video tomorrow, still has up/down be neutral and left/right be neutral.

**Comment by Psyonicpanda** [comment]
https://streamable.com/1qt3qy

**Comment by valignatev** [comment]
yeah I see that input display shows proper socd, but the game doesn't register it, and it's a clear sign that it ignores synthetic inputs, so pretty much the same cause as source engine games. I have trying to trick the system on my tod list so hopefully will get around to that. Once again, thanks for more examples <3

**Comment by Psyonicpanda** [comment]
Hello, sorry for the delay. Yes, this works now. When I hold down and try to jump, I get jump. Holding left+right gives me right. Thank you for your service o7

**Comment by valignatev** [comment]
heyy, glad it helped!
