### ISSUE TITLE
Not working in Fightcade

### ISSUE THREAD

**Issue by kriegisrei** [valignatev/socd#22]
(Just a note it doesn't work anywhere else, but I really only want to use this program for 3rd strike)
3rd strike doesn't have a built in hitbox SOCD style cleaner despite the menu saying it does. I think other CPS-3 games do, but the fc devs removed it for 3s, anyways.
Attached is a video showing my settings and the input display with training mode. Please help me troubleshoot this! Thank you for your time
https://www.youtube.com/watch?v=oPu7O0ZjaCM
I am pressing L+R and U+D in all the clip, I just couldn't get display overlay for OBS to work

**Comment by valignatev** [comment]
Hmm I see that you have Up bound to both Up and Esc, that might be the issue

**Comment by valignatev** [comment]
Oh also if you by any chance have anti-virus triggered at socd-cleaner, it might lead to issues as well. Anti-viruses can modify the executable and prevent it from messing up with keyboard inputs

**Comment by kriegisrei** [comment]
ESC being unbinded didnt do anything, I tried with some flash platformers, type lumina, (i was going to test with sfv but it was updating) and it didn't work there. I only have windows defender and it didn't seem to flag it or anything

**Comment by kriegisrei** [comment]
hmm, found something interesting
i used this https://drakeirving.github.io/MultiKeyDisplay/
![image](https://user-images.githubusercontent.com/38998419/188338171-8483d42d-f02b-4f1f-9fc4-5a79ac9d77e6.png)
this is my results when i press both arrow keys without the program open
![image](https://user-images.githubusercontent.com/38998419/188338193-31f63b87-8081-40d9-b20b-f99863ee296c.png)
but with the program open and both keys being pressed it looks like this
the behavior in game is the same, however

**Comment by valignatev** [comment]
yeah so it works, but the game ignores the input. Some games do ignore injected inputs, not quite sure how to trick them for now. Also the fact that I don't have the games to test them doesn't quite help. I'll keep this issue opened for now as I'm researching ways to trick those games

**Comment by valignatev** [comment]
I've read that a lot of fighting games go out of their way to detect synthetic inputs and drop them as an anti-cheat measure (like to prevent combo macros and such). Do you by any chance know if the games you're trying it in are one of those? I'm thinking whether fighting expensive anti-cheats is something I want to get into or if it should be out of scope for this program

**Comment by kriegisrei** [comment]
I don't believe fightcade has any anticheat. I made a ahk file that works like hitbox style socd and that works fine.

**Comment by valignatev** [comment]
hmm, this is extremely suspicious. Can you please try if it works with old version of socd? This one, for example: https://github.com/valignatev/socd/releases/tag/0.0.7

If not then did you have to do anything special for ahk script to work? Like set any special modes or anything

**Comment by valignatev** [comment]
Oh I've just realized that Fightcade is free and I can test different solutions myself, I'll try to get around to that soon enough

**Comment by kriegisrei** [comment]
fightcade has socd support now
