### ISSUE TITLE
When the down key is "s", it cannot be changed up to any other key

### ISSUE THREAD

**Issue by nxoet** [valignatev/socd#26]
The default WASD and Arrow modes work fine, but when I changed "up" to "spacebar", the left and right of ad are still functional, but the up and down mode of "s spacebar" doesn't work anymore. It seems like when "s" is down, up gets locked to "w". Modifying other keys doesn't work. However, when I changed "down" to another key, like "d", the up and down started working properly.

41
44
57
20
45
D

**Comment by valignatev** [comment]
Hey, thanks for the issue! Can you tell me more about the program/game you're trying it in, and what's that capital D in your config :)

**Comment by nxoet** [comment]
> Hey, thanks for the issue! Can you tell me more about the program/game you're trying it in, and what's that capital D in your config :)

Thank you for responding so quickly. This software hasn't been updated for a long time, so I didn't expect a reply.
 I use this software in some fighting games, currently in Street Fighter 6, to play some charge characters. 
"D" is bound to the Enter key as "ESC", which is automatically generated by the software. The complete code should be "0D".

**Comment by valignatev** [comment]
ohh, you know what, I'm blind. 4th number in the config is not up, it's down. So you're assigning down to spacebar here, not up.

So, a - left, d- right, s - down, space - up would be this:
```
41
44
20
53
```

**Comment by nxoet** [comment]
> 

Thank you, it's working.

**Comment by valignatev** [comment]
ur welcome, it's really my fault, this config file is so bad :) I have a version of the program that can bind keys with UI, but it's undercooked. Anyway, I'm glad it's working for you
