### ISSUE TITLE
Not working on specific games that block input from external softwares

### ISSUE THREAD

**Issue by littlewhite29** [valignatev/socd#27]
I notice that in some games this software is not working. 
In recent updates (May be on January 6th? Because it is still working while i was playing on January 5th ), Street Fighter 6 seems to have blocked input from external softwares (or maybe other softwares just cannot listen to the keyboard? ) , And i find hotkeys of other software (my scrennshot software for example) is not working as well .  I remember that in other games like KOF02UM the software is not working either.  
I would like to know if there is a solution to this, or maybe I can only seek other solutions like hitbox ?

**Comment by valignatev** [comment]
Hey, thanks for the report! Yeah, unfortunately, games can detect "injected" software-level inputs and straight-up rejecting them. It's their way of banning macros and stuff like that. The only way to get around it would be to inject these inputs on a driver level, but on windows only signed drivers can be installed by default, and microsoft demands $$$ for that :(

So for now idk if there's a way to fix this, maybe there are some signed programmable drivers, I might look into that

**Comment by littlewhite29** [comment]
I see. 
Now im going to try some keyboard marcro programming things, like  USB adapter that can transfer a normal keyboard to a keyboard supports marcro programming things .
For this issue can hardly be fixed by normal ways , i think it is done , thank you.
