### ISSUE TITLE
Is your software usable for valorant 

### ISSUE THREAD

**Issue by Sachinanand99** [valignatev/socd#29]
can i use your program to use in games like valorant or cs go for the features like razer or woot keyboard provides...😊. Also how to apply your program for only a and d keyboard only and not for w and s.

**Comment by valignatev** [comment]
For the first question - it might work depending on how those games handle inputs. For the second question - not directly. You can set w and s keys to something bogus you never use, but that's kind of a workaround.

Btw, I'm currently rewriting the whole thing where up/down and left/right will be individually configurable, but that rewrite isn't finished yet.

**Comment by znarfm** [comment]
It is working on Valorant. In my case, I had to run the program as an administrator for it to work.

**Comment by Sneophron** [comment]
Just run it administrator and u can use now with no problems

**Comment by zalUoU** [comment]
It isn't working in VALORANT for me for some reason. And idk if it's supposed to work globally too. Because when I try it on notepad, It doesn't work for me. What do I do in this case?

**Comment by valignatev** [comment]
@zalUoU if you dropped it into Program Files or into some other restricted folder on disk C: then you have to run it as Administrator.

**Comment by zalUoU** [comment]
i didn't drop it anywhere restricted. It's literally in my downloads folder, and I'm running it as administrator too. But it still doesn't work.

**Comment by Sachinanand99** [comment]
https://github.com/cafali/SnapKey/releases/tag/v1.1.6 found this

**Comment by zalUoU** [comment]
> https://github.com/cafali/SnapKey/releases/tag/v1.1.6 found this

i believe this is a different program and has a different function compared to the SOCD Cleaner no?

**Comment by Sachinanand99** [comment]
> > https://github.com/cafali/SnapKey/releases/tag/v1.1.6 found this
> 
> i believe this is a different program and has a different function compared to the SOCD Cleaner no?

I think it is working same as i used both.

**Comment by valignatev** [comment]
Briefly looking at the code, the programs are similar. Mine does a bit more stuff around the currently focused program detection, but otherwise keyboard hooks look similar enough.

**Comment by valignatev** [comment]
> Is there any difference in the speed of programs

In this particular case, you won't notice any difference.

> How to minimize your program to system tray

You can put it in autorun and it'll work, but there's no way to minimize it into the tray for now. I have it as a todo for the rewrite.

> can you make a program that will act as a driver

Technically yes, but you can't run unsigned drivers on Windows by default, I would have to require users to boot into a mode that allows unsigned drivers. And signing the driver costs a lot of money that I'm not willing to spend :(

**Comment by nevejaa** [comment]
it is bannable in valorant?
