### ISSUE TITLE
Is it bannable?

### ISSUE THREAD

**Issue by Magussi** [valignatev/socd#31]
I've heard stories of people getting banned from using these kinds of softwares but does that actually happen? is there a risk to using it in something like valorant or cs2?

**Comment by iwnlLevi** [comment]
Did you run this on your computer? have some problem or virus?

**Comment by Magussi** [comment]
I've not been banned myself. I've just heard it's bannable. Or is it just "banned" from competitive play in esports?

**Comment by valignatev** [comment]
Let's just say that kernel-level anti-cheats are likely to be able to detect it. Is it actually bannable? Idk, check tos of the game you're playing.
