### ISSUE TITLE
Is this still up?

### ISSUE THREAD

**Issue by Nikkolas-Cage** [valignatev/socd#37]
has anyone tested this yet in 2024?

**Comment by valignatev** [comment]
Should still be working, let me know if it doesn't work for you. Also, I'm working on a rewrite in my spare time, so that'll happen some time soon.

**Comment by Lee-The-Tree** [comment]
thanks for your work. and yea it does currently still function fine. looking forward to the rebuild. 👍

**Comment by ThisIsEXE01** [comment]
> Should still be working, let me know if it doesn't work for you. Also, I'm working on a rewrite in my spare time, so that'll happen some time soon.

Unlike SnapKey, which apparently works like AHK, your program works with all games! I hope the program will work just as well in the new version. Will the new version be in C or C++?

**Comment by valignatev** [comment]
It'll be in jai - see "rewrite" branch.
