### ISSUE TITLE
SOCD Permanently on?

### ISSUE THREAD

**Issue by Supersoakem** [valignatev/socd#43]
Ok so I play CS2 and tried this out. The disable option worked fine and I was good. I then discovered while playing the exe was never opened before I started the game. I was like maybe the program starts when I load up my pc. Well cs2 released a new update banning it from the game, which I got kicked from a game because of it. I tried to open the program, disable the binds, change the config to work in other programs besides it. I deleted the program along with the config and no matter what it’s acting like it’s running in the background. Did I do something wrong lol. Like is this script bound to just the program or did it change any settings in windows I need to delete or change? Even though I didn’t get kicked from any more games after I deleted it but it’s literally still working lol. I don’t use any other programs or never have that changes anything related to this. I just don’t wanna get banned because of it now that it’s been blacklisted. Any help please :/

**Comment by Supersoakem** [comment]
Your program is the only I have ever downloaded remotely messing with keys. All I can say is I ran that batch file or whatever you had from the source code compiler. That was by accident which I don’t use or even know what it does or is for. Other than that, no cheats, no special programs, nothing. I did some testing this morning. Joined a game without opening it. It was beautiful instant STOP when pressing opposite movement key and purposely kept doing it over and over. I then opened the program which seemed to disable the key overriding but within a few seconds I get instantly kicked for “key input automation”. Lol

**Comment by valignatev** [comment]
The batch file just builds the program from source code (assuming you mean `build.bat`).
And yeah, socd uses low level keyboard hooks to override inputs, and they are easily detectable. So if the program wants to do it - it can. I don't have any plans to try and fool this kind of detection for now.

**Comment by valignatev** [comment]
Whatever there is, it's definitely not related to this program. You can check running processes in task manager, maybe something there will hint you to the problem

**Comment by Supersoakem** [comment]
Ok I appreciate your help and your work on the program! It could even be as simple as a certified commonly used program interfering with it. I just thought I’d try and weed out any other possible issues direct from the source. Before moving on to other possibilities. Thank you again.
