### ISSUE TITLE
SOCD works constantly

### ISSUE THREAD

**Issue by murzqwe** [valignatev/socd#45]
I used SOCD as usual, and at one point it started working even when I didn’t open it, now I want to stop using SOCD, but I can’t and don’t know how to turn it off
HELP PLS!

**Comment by valignatev** [comment]
Closing the program should clean up all the hooks. Are you sure you're not using any other similar programs? You can double-check in task manager if socd still running.

**Comment by murzqwe** [comment]
I checked everything possible, socd is not running anywhere, but the character still stops when you hold down a and d, I didn’t use other programs

**Comment by murzqwe** [comment]
But when I run socd in wasd mode, everything becomes default, but if I close it, it will be in working order again

**Comment by valignatev** [comment]
I'm so confused now. What do you mean "the character still stops when you hold down a and d". This is the default behavior when the program is closed. At least in most games. What socd does, when it is turned on, it makes the last button you pressed take precedence. So if you pressed a, and then pressed d, while still holding a, your character will go to the right.

**Comment by murzqwe** [comment]
I figured it out, I'm stupid and at first I didn't understand what exactly socd does, but now I understand, I apologize for wasting your time and thank you

**Comment by valignatev** [comment]
Don't worry about it, better be safe than sorry :)
