### ISSUE TITLE
small problem

### ISSUE THREAD

**Issue by idkasdfasdf** [valignatev/socd#50]
it works, but when i use a macro creator to see the inputs, if you hold a then press d and never let go of a, the a will get pressed again for a very short time after the d input. idk how impactful this is. 
![image_2024-10-28_211217821](https://github.com/user-attachments/assets/44475e16-f581-4de3-af18-c3a06b401960)

**Comment by valignatev** [comment]
I'm not sure I understand what I'm looking at. You would definitely be able to see that in game if a wrong input were getting pressed.

**Comment by idkasdfasdf** [comment]
When the d button is pressed, on the side it shows the down arrow, you can see that the a is pressed 0.001 seconds after the d button is pressed

**Comment by idkasdfasdf** [comment]
i will test it in game though

**Comment by valignatev** [comment]
Ah, I see. This shouldn't happen, let me know if you see issues in games. Maybe this macro software does something weird, or maybe I actually have a bug :)

**Comment by idkasdfasdf** [comment]
idk it doesnt show in game but the macro software shows it. i dont think this is a problem
